//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurSite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TServices
    {
        public byte ID { get; set; }
        public string ResimYolu { get; set; }
        public string Ulke { get; set; }
        public string Adres { get; set; }
        public string ZamanDilimi { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
